MovieMVC.General/Models/Request/Movie/MoviePostRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieMVC.General.Models.Request.Movie
{
    public class MoviePostRequest
    {
        public int Id { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [Display(Name = "Produced Year")]
        [Required(ErrorMessage = "Produced Year is required")]
        public int ProducedYear { get; set; }

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Movie Description is required")]
        public string Description { get; set; }

        [Display(Name = "Poster URL")]
        [Required(ErrorMessage = "Movie poster URL is required")]
        public string PosterUrl { get; set; }

        [Display(Name = "Movie start date")]
        [Required (ErrorMessage = "Start date is required")]
        public DateTime StartDate { get; set; }

        [Display(Name = "Movie end date")]
        [Required(ErrorMessage = "End date is required")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Subject")]
        [Required(ErrorMessage = "Subject is required")]
        public string Subject { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Price is required")]
        public double MoviePrice { get; set; }

        public bool IsActive { get; set; }
   
    }
}

MovieMVC.General/Models/Request/Movie/MoviePutRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieMVC.General.Models.Request.Movie
{
    public class MoviePutRequest
    {
        public int Id { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [Display(Name = "Produced Year")]
        [Required(ErrorMessage = "Produced Year is required")]
        public int ProducedYear { get; set; }

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Movie Description is required")]
        public string Description { get; set; }

        [Display(Name = "Poster URL")]
        [Required(ErrorMessage = "Movie poster URL is required")]
        public string PosterUrl { get; set; }

        [Display(Name = "Movie start date")]
        [Required(ErrorMessage = "Start date is required")]
        public DateTime StartDate { get; set; }

        [Display(Name = "Movie end date")]
        [Required(ErrorMessage = "End date is required")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Subject")]
        [Required(ErrorMessage = "Subject is required")]
        public string Subject { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Price is required")]
        public double MoviePrice { get; set; }

        public bool IsActive { get; set; }        
    }
}

MovieMVC.General/Controllers/MovieController.cs
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieMVC.Service.Abstractions;
using MovieMVC.Service.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MovieMVC.General.Models.Response;
using MovieMVC.General.Models.Request.Movie;

namespace MovieMVC.General.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _service;    

        public MovieController(IMovieService service)
        {
            _service = service;         
        }
        public IActionResult Index()
        {
            var result = _service.GetAllAsync();
            var moviesDTO = result.Adapt<List<MovieDTO>>();
            
            return View(moviesDTO);
        }
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null)
            {
                return View("NotFound");
            }

            ViewBag.Suggestions = result;

            return View(result);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult NonActive()
        {
            var result = _service.GetAllNonActiveAsync();
            var moviesDTO = result.Adapt<List<MovieDTO>>();
            return View(moviesDTO);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Activate(int id)
        {
            await _service.PublishMovieAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Deactivate(int id)
        {
            await _service.DeactivateMovieAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin,Manager")]
        public IActionResult Archive()
        {
            var result = _service.GetAllArchiveAsync();
            var moviesDTO = result.Adapt<List<MovieDTO>>();
            return View(moviesDTO);
        }

        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Create(MoviePostRequest movie)
        {
            var newMovie = movie.Adapt<MovieServiceModel>();
            if (!ModelState.IsValid)
            {
                return View(movie);
            }
            await _service.CreateAsync(newMovie);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Edit(MovieServiceModel movie)
        {
            await _service.UpdateAsync(movie);

            if (!ModelState.IsValid)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

MovieMVC.General/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieMVC.General.Infrastructure.Sessions;
using MovieMVC.Service.Abstractions;
using MovieWebApi.Domain.POCO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieWebApi.Domain.POCO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MovieMVC.General.Infrastructure.Sessions;

namespace MovieMVC.General.Controllers
{
    public class OrderController : Controller
    {
        private readonly IMovieService _service;
        private readonly IOrdersService _orders;
        public OrderController(IMovieService service, IOrdersService orders)
        {
            _service = service;
            _orders = orders;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            
            var orders = await _orders.GetOrdersByUserAsync(userId);
            return View(orders);
        }
        [Authorize]
        public async Task<IActionResult> CompleteOrder()
        {
            var items = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string mail = User.FindFirstValue(ClaimTypes.Email);
            var order = new Order(){
                UserId=userId,
                Email=mail
            };


            var list = new List<OrderMovie>();
            foreach (var item in items)
            {
                list.Add(new OrderMovie
                {
                    Amount = item.amount,
                    MovieId = item.movie.Id,
                    OrderId = order.Id,
                    Price = item.movie.Price
                });
            }
            await _orders.StoreOrderAsync(order, list);

            List<ShoppingCartItem> cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");
            cart.Clear();
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);


            return View("OrderCompleted");
        }

        public IActionResult ShoppingCart()
        {            
            var cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");
            // if(cart.Any(item=>item.movie)==null) return RedirectToAction(nameof(Index));

            try
            {
                var response = new ShoppingCartViewModel()
                {
                    ShoppingCartItem = cart,
                    ShoppingCartTotal = cart.Sum(item => item.movie.Price * item.amount)
                };


                return View(response);
            }
            catch(Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
        }
    
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            if (string.IsNullOrEmpty(id.ToString())||id==0) return RedirectToAction(nameof(Index));


            var productModel = await _service.GetByIdAsync(id);
            if (SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart") == null)
            {
                List<ShoppingCartItem> cart = new List<ShoppingCartItem>();
                cart.Add(new ShoppingCartItem { movie= productModel, amount = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<ShoppingCartItem> cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].amount++;
                }
                else
                {
                    cart.Add(new ShoppingCartItem { movie = productModel, amount = 1 });
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction(nameof(ShoppingCart));
           
        }

        public IActionResult RemoveItemFromShoppingCart(int id)
        {
            List<ShoppingCartItem> cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction(nameof(ShoppingCart));
            
        }
        private int isExist(int id)
        {
            List<ShoppingCartItem> cart = SessionHelper.GetObjectFromJson<List<ShoppingCartItem>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].movie.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

MovieMVC.General/Views/Movie/Archive.cshtml
@using MovieMVC.Service.Models
@using MovieMVC.General.Models.Response
@model IEnumerable<MovieDTO>

@{
    ViewData["Title"] = "List of Movies";
}
    <div class="text-white">
    <a asp-controller="Movie" asp-action="Create" class="btn btn-success">

        <i class="bi bi-plus-circle">

        </i>
        Add New
    </a>
</div>
<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-dark">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Title
                                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.MovieId"><i class="bi bi-pencil-square"></i></a>
                                    }*@
                                    <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                </h5>

                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.PosterUrl" width="100%" alt="@item.Title">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">

                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM ")</p>

                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                @*<a class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")" 
                                   asp-controller="Orders" 
                                   asp-action="AddItemToShoppingCart" 
                                   asp-route-id="@item.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))</a>*@
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<h1>Movie View-Index</h1>

MovieMVC.General/Views/Movie/Create.cshtml
@using MovieMVC.General.Models.Request.Movie
@model MoviePostRequest

@{
    ViewData["Title"] = "Create a new Movie";
}


<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MoviePrice" class="control-label"></label>
                                <input asp-for="MoviePrice" type="number" step="any" class="form-control" />
                                <span asp-validation-for="MoviePrice" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PosterUrl" class="control-label"></label>
                                <input asp-for="PosterUrl" class="form-control" />
                                <span asp-validation-for="PosterUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $("#PosterUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

MovieMVC.General/Views/Movie/Details.cshtml

@model MovieWebApi.Domain.POCO.Movies

@{
    ViewData["Title"] = "Movie details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Title
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.PosterUrl" width="100%" alt="@Model.Title">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>                      

                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                           @* <a class="btn btn-success text-white  @((DateTime.Now > Model.EndDate) ? "disabled" : "")" 
                               asp-controller="Orders" 
                               asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>*@
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">

        @*<a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@model.Id">
         <div class="ccol-md-4 col-xs-6 border-primary mb-3">
             <div class="card mb-3" style="max-width: 240px;">
                                 <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-dark">
                        <img src="@item.MoviePoster" width="100%" alt="@item.Title">
                        </div>
                    </div>
                  </div>
              </div>
          </div>
       </a>*@       
    
</div>

MovieMVC.General/Views/Movie/Index.cshtml
@using MovieMVC.Service.Models
@using MovieMVC.General.Models.Response
@model IEnumerable<MovieDTO>

@{
    ViewData["Title"] = "List of Movies";
}
@if (User.IsInRole("Admin") || User.IsInRole("Manager"))
{
    <div class="text-white">
        <a asp-controller="Movie" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle">
            </i>
            Add New
        </a>
    </div>
}


<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-dark">
                            <p class="card-text">
                                <h5 class="card-title">
                                     @if(User.IsInRole("Admin")){
                                    <a class="text-white float-left" asp-action="Deactivate" asp-route-id="@item.Id"><i class="bi bi-slash-circle-fill"></i></a>
                                     }
                                    @item.Title
                                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.MovieId"><i class="bi bi-pencil-square"></i></a>
                                    }*@
                                   @if(User.IsInRole("Manager")){
                                     <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                     }
                                </h5>

                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.PosterUrl" width="100%" alt="@item.Title">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Subject</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM ")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Details
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")" 
                                   asp-controller="Order" 
                                   asp-action="AddItemToShoppingCart" 
                                   asp-route-id="@item.Id">
                                <i class="bi bi-cart-plus"></i> Price @item.MoviePrice.ToString("c")</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<h1>Movie View-Index</h1>

MovieMVC.General/Views/Movie/NonActive.cshtml
@using MovieMVC.Service.Models
@using MovieMVC.General.Models.Response
@model IEnumerable<MovieDTO>

@{
    ViewData["Title"] = "List of Movies";
}
<div class="text-white">
    <a asp-controller="Movie" asp-action="Create" class="btn btn-success">

        <i class="bi bi-plus-circle">

        </i>
        Add New
    </a>
</div>
<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-dark">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Title
                                    @*@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                        {
                                            <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.MovieId"><i class="bi bi-pencil-square"></i></a>
                                        }*@
                                    <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                </h5>

                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.PosterUrl" width="100%" alt="@item.Title">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM ")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-left" asp-action="Activate" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Activate
                                </a>
                                <a class="btn btn-outline-primary float-right" asp-action="Delete" asp-route-id="@item.Id">
                                    <i class="bi bi-backspace-reverse-fill"></i> Delete
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<h1>Movie View-Index</h1>